### ISSUE TITLE
pi zero w and pi zero 2 w dtbo files

### ISSUE THREAD

**Issue by lambtor** [waveshare/2.8inch-DSI-LCD#1]
If this is the wrong repository for this screen please let me know, as the link on the readme goes to 404:
https://www.waveshare.com/product/displays/lcd-oled/lcd-oled-2/2.8inch-hdmi-lcd-h.htm

Is there a dtbo for the pi zero w and the pi zero 2 w?  Would the 3b dtbo work for either of these?

**Comment by waveshare** [comment]
Hello,
Sorry for the late reply
Our dtbo is compatible with all versions of pi, you can refer to our wiki to operate
https://www.waveshare.com/wiki/2.8inch_HDMI_LCD_(H)_

If you encounter other problems, please contact the work order to get better after-sales service
support@waveshare.com

**Comment by lambtor** [comment]
thanks! existing dtbo does work for me on pi zero 2.
